# Generated by Django 6.0 on 2025-12-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_authtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'permissions': [('mark_attendance', 'Can mark attendance'), ('update_attendance', 'Can update attendance'), ('view_attendance_report', 'Can view attendance reports')]},
        ),
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
