# Generated by Django 6.0 on 2025-12-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='can_login',
            field=models.BooleanField(default=True),
        ),
    ]
